-- MySQL Script generated by MySQL Workbench
-- Tue Nov 19 16:56:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tielen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tielen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tielen` DEFAULT CHARACTER SET utf8 ;
USE `tielen` ;

-- -----------------------------------------------------
-- Table `tielen`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tielen`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `mail` VARCHAR(255) NULL,
  `reponse` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tielen`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tielen`.`messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NULL,
  `date` VARCHAR(255) NULL,
  `id_user` INT(11) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `id_user`
    FOREIGN KEY ()
    REFERENCES `tielen`.`users` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
